name: Auto Merge and Cleanup

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  auto-merge:
    if: github.actor == 'MarkBedrock' || github.actor == 'UnderLord'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR
        uses: actions/github-script@v8
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            // Check if all required status checks are passing
            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha
            });
            
            const requiredChecks = ['CI', 'CodeQL'];
            const allChecksPassing = requiredChecks.every(checkName => {
              const check = checks.check_runs.find(c => c.name === checkName);
              return check && check.conclusion === 'success';
            });
            
            if (allChecksPassing) {
              console.log('All required checks passed, auto-merging...');
              
              // Merge the PR with squash
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                merge_method: 'squash',
                commit_title: `Auto-merge: ${pr.title}`,
                commit_message: `Automatically merged PR #${context.issue.number}\n\n${pr.body || ''}`
              });
              
              console.log('PR merged successfully');
              
              // Delete the source branch
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${pr.head.ref}`
              });
              
              console.log(`Branch ${pr.head.ref} deleted successfully`);
            } else {
              console.log('Required checks not yet passing, waiting...');
            }

