name: Bedrock CI (S3 smoke test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  s3-smoke:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::260287419934:role/BedrockGitHubActionsRole
          aws-region: us-east-2

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Upload test artifact
        run: |
          echo "ci test $(date -Is)" > ci.txt
          aws s3 cp ci.txt s3://phoenix-dev-artifacts-us-east-2-mn/ci/bedrock/ci.txt

      - name: Verify artifact
        run: aws s3 ls s3://phoenix-dev-artifacts-us-east-2-mn/ci/bedrock/
